### ISSUE TITLE
Pairwise plot seems to have issues with recent seaborn

### ISSUE THREAD

**Issue by mvdbeek** [asntech/intervene#12]
I'm seeing the following traceback if I set `htype` to dendrogram:
```
Traceback (most recent call last):
  File "/Users/mvandenb/miniconda3/envs/__intervene@0.6.4/bin/intervene", line 606, in <module>
    main()
  File "/Users/mvandenb/miniconda3/envs/__intervene@0.6.4/bin/intervene", line 426, in main
    pairwise.pairwise_intersection(label_names, options)
  File "/Users/mvandenb/miniconda3/envs/__intervene@0.6.4/lib/python3.6/site-packages/intervene/modules/pairwise/pairwise.py", line 478, in pairwise_intersection
    heatmap_dendrogram(matrix,outfile, options)
  File "/Users/mvandenb/miniconda3/envs/__intervene@0.6.4/lib/python3.6/site-packages/intervene/modules/pairwise/pairwise.py", line 304, in heatmap_dendrogram
    sns.plt.setp(sns_plot.ax_heatmap.yaxis.get_majorticklabels(), rotation=0)
AttributeError: module 'seaborn' has no attribute 'plt'
```
I have seen that sns.plt is not part of the seaborn API anymore (https://stackoverflow.com/questions/45070959/atributeerror-module-object-has-no-attribute-plt-seaborn)

**Comment by asntech** [comment]
Apologies for the delay. I will check the pull request and merge. Thanks!!

**Comment by jdamas13** [comment]
I'm finding the same issue when running pairwise dendrogram mode on the docker image asntech/intervene:v0.6.5.
Is there a newer version that fixed it? Thanks!
