### ISSUE TITLE
how to display the "--reldist" result? 

### ISSUE THREAD

**Issue by clouds-drift** [asntech/intervene#16]
I'm trying to use the "--reldist" calculation. 
 _**intervene pairwise --compute reldist --sort --test**_

Then it returns error:
Running Intervene with test data.

Performing a pairwise intersection analysis. Please wait...

Traceback (most recent call last):
  File "/export/data2/anaconda2/bin/intervene", line 4, in <module>
    __import__('pkg_resources').run_script('intervene==0.6.4', 'intervene')
  File "/export/data2/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/export/data2/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/export/data2/anaconda2/lib/python2.7/site-packages/intervene-0.6.4-py2.7.egg/EGG-INFO/scripts/intervene", line 606, in <module>
    main()
  File "/export/data2/anaconda2/lib/python2.7/site-packages/intervene-0.6.4-py2.7.egg/EGG-INFO/scripts/intervene", line 426, in main
    pairwise.pairwise_intersection(label_names, options)
  File "/export/data2/anaconda2/lib/python2.7/site-packages/intervene-0.6.4-py2.7.egg/intervene/modules/pairwise/pairwise.py", line 412, in pairwise_intersection
    matrix, bed_sizes = create_matrix(beds=options.input, bed_names=label_names, func=FUNC, verbose=False, sort_bed=options.sort, **kwoptions)
  File "/export/data2/anaconda2/lib/python2.7/site-packages/intervene-0.6.4-py2.7.egg/intervene/modules/pairwise/pairwise.py", line 74, in create_matrix
    matrix[bed_names[ia]][bed_names[ib]] = func(a, b, **kwoptions)
  File "/export/data2/anaconda2/lib/python2.7/site-packages/intervene-0.6.4-py2.7.egg/intervene/modules/pairwise/pairwise.py", line 41, in reldist_of_a
    return float(sum(a.reldist(b)['reldist'])) / max(len(a.reldist(b)['reldist']), 1)
  File "/export/data2/anaconda2/lib/python2.7/site-packages/pybedtools/bedtool.py", line 349, in wrapped
    return does_not_return_bedtool(stream, **kwargs)
  File "/export/data2/anaconda2/lib/python2.7/site-packages/pybedtools/bedtool.py", line 69, in _reldist_output_handler
    header = six.advance_iterator(iterable).split()
StopIteration

**Comment by asntech** [comment]
Apologies for the late response. Can you try by reinstalling pybedtools?
