### ISSUE TITLE
ImportError: cannot import name 'get_backend'

### ISSUE THREAD

**Issue by dpolychr** [asntech/intervene#20]
Dear @asntech,

When running the example code for intervene, I am getting:

```
intervene venn -i intervene/example_data/ENCODE_hESC/*.bed
Traceback (most recent call last):
  File "/anaconda3/bin/intervene", line 4, in <module>
    _import_('pkg_resources').run_script('intervene==0.6.4', 'intervene')
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/_init_.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/_init_.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/anaconda3/lib/python3.6/site-packages/intervene-0.6.4-py3.6.egg/EGG-INFO/scripts/intervene", line 13, in <module>
    from matplotlib import use as mpl_use
  File "/anaconda3/lib/python3.6/site-packages/matplotlib/_init_.py", line 1111, in <module>
    rcParamsOrig = RcParams(rcParams.copy())
  File "/anaconda3/lib/python3.6/site-packages/matplotlib/_init.py", line 891, in __getitem_
    from matplotlib import pyplot as plt
  File "/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/anaconda3/lib/python3.6/site-packages/matplotlib/colorbar.py", line 40, in <module>
    import matplotlib._constrained_layout as constrained_layout
  File "/anaconda3/lib/python3.6/site-packages/matplotlib/_constrained_layout.py", line 52, in <module>
    from matplotlib.legend import Legend
  File "/anaconda3/lib/python3.6/site-packages/matplotlib/legend.py", line 43, in <module>
    from matplotlib.offsetbox import HPacker, VPacker, TextArea, DrawingArea
  File "/anaconda3/lib/python3.6/site-packages/matplotlib/offsetbox.py", line 33, in <module>
    from matplotlib.image import BboxImage
  File "/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 19, in <module>
    from matplotlib.backend_bases import FigureCanvasBase
  File "/anaconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 46, in <module>
    from matplotlib import (
ImportError: cannot import name 'get_backend'
```
I have matplotlib '3.0.3' and python 3.7 

Any advice would be much appreciated.

Many thanks,
Dimitris

**Comment by dpolychr** [comment]
Hi @asntech, 

I uninstalled and installed again matplotlib and it magically worked.

Thanks,
Dimitris

**Comment by asntech** [comment]
Hi Dimitris,

Thanks for letting me know!! 👍

Best,
Aziz
