### ISSUE TITLE
intervene venn with lists does not work

### ISSUE THREAD

**Issue by ashleymaeconard** [asntech/intervene#32]
Hi - I am getting odd errors when running venn on several gene lists. I tried 2 ways:

1) **One list (.csv)**
On your readthedocs: 

> List type data: List data is a correctly formatted csv/text file, with lists of names. Each column represents a set, and each row represents an element (names/gene/SNPs). Header names (first row) will be used as set names.

Thus, with `test.csv` which looks like:
```
l1,l2,l3
a,b,c
c,a,a
s,d,g
```

I run:

`intervene venn -i test.csv --type list`, and 

error output is `Input should have at least two files`.

So I tried:
2) **Two lists:**

`test.txt` has

```
l1
a
b
c
```
and 

`test2.txt` has
```
l2
b
a
d
``` 

I run: 
`intervene venn -i test.txt test1.txt --type list`, and

error output is:

```
Generating a 2-way "venn" diagram. Please wait...
Traceback (most recent call last):
  File "/Users/ashleymaeconard/anaconda2/envs/timeor_env2/bin/intervene", line 4, in <module>
    __import__('pkg_resources').run_script('intervene==0.5.8', 'intervene')
  File "/Users/ashleymaeconard/anaconda2/envs/timeor_env2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/ashleymaeconard/anaconda2/envs/timeor_env2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/Users/ashleymaeconard/anaconda2/envs/timeor_env2/lib/python2.7/site-packages/intervene-0.5.8-py2.7.egg-info/scripts/intervene", line 543, in <module>
    main()
  File "/Users/ashleymaeconard/anaconda2/envs/timeor_env2/lib/python2.7/site-packages/intervene-0.5.8-py2.7.egg-info/scripts/intervene", line 417, in main
    a = open(options.a, 'r').read().splitlines()
AttributeError: 'Namespace' object has no attribute 'a'

```

**Comment by asntech** [comment]
It seems you're using `intervene==0.5.8`. Please go ahead and update to the latest version.

`conda update intervene`
OR 
`conda install -c bioconda intervene=0.6.4`

**Comment by ashleymaeconard** [comment]
Thank you! Ah too bad, it looks like I have to fix these conflicting packages before I do anything! Thank you for your prompt response nevertheless!
```
(timeor_env2) ashleymaeconard@amc:~$ conda install -c bioconda intervene=0.6.4
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package sqlite conflicts for:
python==2.7.17=h97142e2_0 -> sqlite[version='>=3.30.0,<4.0a0']
Package r-upsetr conflicts for:
intervene=0.6.4 -> r-upsetr
Package seaborn conflicts for:
intervene=0.6.4 -> seaborn
Package ncurses conflicts for:
python==2.7.17=h97142e2_0 -> ncurses[version='>=6.1,<7.0a0']
Package r-cairo conflicts for:
intervene=0.6.4 -> r-cairo
Package zlib conflicts for:
python==2.7.17=h97142e2_0 -> zlib[version='>=1.2.11,<1.3.0a0']
Package pybedtools conflicts for:
intervene=0.6.4 -> pybedtools
Package matplotlib conflicts for:
intervene=0.6.4 -> matplotlib
Package readline conflicts for:
python==2.7.17=h97142e2_0 -> readline[version='>=7.0,<8.0a0']
Package pip conflicts for:
python==2.7.17=h97142e2_0 -> pip
Package r-base conflicts for:
intervene=0.6.4 -> r-base
Package scipy conflicts for:
intervene=0.6.4 -> scipy
Package ca-certificates conflicts for:
python==2.7.17=h97142e2_0 -> ca-certificates
Package tk conflicts for:
python==2.7.17=h97142e2_0 -> tk[version='>=8.6.8,<8.7.0a0']
Package r-corrplot conflicts for:
intervene=0.6.4 -> r-corrplot
Package libffi conflicts for:
python==2.7.17=h97142e2_0 -> libffi[version='>=3.2.1,<4.0a0']
Package bedtools conflicts for:
intervene=0.6.4 -> bedtools
Package r conflicts for:
intervene=0.6.4 -> r=3.4.1
Package numpy conflicts for:
intervene=0.6.4 -> numpy
Package pandas conflicts for:
intervene=0.6.4 -> pandas[version='<1']
Package matplotlib-base conflicts for:
intervene=0.6.4 -> matplotlib-base
```

**Comment by ashleymaeconard** [comment]
I wanted to post the solution I used a while back in the event that it is useful!

Using `conda update intervene` still left me with the 0.5.8 intervene version. 

I just installed the development version from Bitbucket to get intervene version 0.6.4:
```
git clone https://bitbucket.org/CBGR/intervene.git
cd intervene
python setup.py sdist install
```
The only difference if you prefer the development version from Github is 
`git clone https://github.com/asntech/intervene.git`

**Comment by amizeranschi** [comment]
@ashleymaeconard 

For the record, running

```
conda install -c bioconda intervene=0.6.4
```

should force it to install version `0.6.4`, if possible. If that doesn't work, for whatever reason, then the solution would be to create a new conda environment and install intervene into it.
