### ISSUE TITLE
fail to use pairwise comands

### ISSUE THREAD

**Issue by unique379** [asntech/intervene#39]
Hi 
I install intervene using conda and its working with plotting commands but not the pairwise. even with test its failing, please can you tell me whats wrong here? or bugs ??

intervene pairwise --test

Running Intervene with test data.

Performing a pairwise intersection analysis. Please wait...

Traceback (most recent call last):
  File "/Users/rupeshk/miniconda3/envs/intervane/bin/intervene", line 4, in <module>
    __import__('pkg_resources').run_script('intervene==0.5.8', 'intervene')
  File "/Users/rupeshk/miniconda3/envs/intervane/lib/python3.6/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/rupeshk/miniconda3/envs/intervane/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/Users/rupeshk/miniconda3/envs/intervane/lib/python3.6/site-packages/intervene-0.5.8-py3.6.egg-info/scripts/intervene", line 543, in <module>
    main()
  File "/Users/rupeshk/miniconda3/envs/intervane/lib/python3.6/site-packages/intervene-0.5.8-py3.6.egg-info/scripts/intervene", line 355, in main
    pairwise.pairwise_intersection(options)
  File "/Users/rupeshk/miniconda3/envs/intervane/lib/python3.6/site-packages/intervene/modules/pairwise/pairwise.py", line 454, in pairwise_intersection
    matrix = pd.read_table(matrix_file,index_col=0, delim_whitespace=True)
  File "/Users/rupeshk/miniconda3/envs/intervane/lib/python3.6/site-packages/pandas/io/parsers.py", line 755, in read_table
    return read_csv(**locals())
  File "/Users/rupeshk/miniconda3/envs/intervane/lib/python3.6/site-packages/pandas/io/parsers.py", line 625, in read_csv
    "Specified a delimiter with both sep and "
ValueError: Specified a delimiter with both sep and delim_whitespace=True; you can only specify one.

**Comment by bioinfouser** [comment]
I am not the owner of intervene, but it works with python 2.7. Just make a new conda environment and reinstall. It should run

**Comment by asntech** [comment]
@unique379 It seems you're using an old version `0.5.8`. Can you please try the latest version from `bioconda` 

`conda install -c bioconda intervene=0.6.4`

or install it from the source.
