### ISSUE TITLE
 intervene pairwise: ValueError: keyword grid_b is not recognized;

### ISSUE THREAD

**Issue by Edert** [asntech/intervene#56]
Hi,

I would like to use the pairwise mode via:

intervene pairwise -i indata/*.bed -o results/pairwise_all --compute=jaccard

However, it looks like the grid_b parameter in matplotlib is deprecated:

```
Performing a pairwise intersection analysis. Please wait...

Traceback (most recent call last):
  File "/apps/miniconda3/bin/intervene", line 604, in <module>
    main()
  File "/apps/miniconda3/bin/intervene", line 424, in main
    pairwise.pairwise_intersection(label_names, options)
  File "/apps/miniconda3/lib/python3.9/site-packages/intervene/modules/pairwise/pairwise.py", line 486, in pairwise_intersection
    barplot(series, matrix, outfile, options, max_size=max(bed_sizes))
  File "/apps/miniconda3/lib/python3.9/site-packages/intervene/modules/pairwise/pairwise.py", line 165, in barplot
    ax.grid(b=False, which='major', axis='both', alpha=0.1)
  File "/apps/miniconda3/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 3194, in grid
    self.xaxis.grid(visible, which=which, **kwargs)
  File "/apps/miniconda3/lib/python3.9/site-packages/matplotlib/axis.py", line 1660, in grid
    self.set_tick_params(which='major', **gridkw)
  File "/apps/miniconda3/lib/python3.9/site-packages/matplotlib/axis.py", line 932, in set_tick_params
    kwtrans = self._translate_tick_params(kwargs)
  File "/apps/miniconda3/lib/python3.9/site-packages/matplotlib/axis.py", line 1076, in _translate_tick_params
    raise ValueError(
ValueError: keyword grid_b is not recognized; valid keywords are ['size', 'width', 'color', 'tickdir', 'pad', 'labelsize', 'labelcolor', 'zordeck1On', 'tick2On', 'label1On', 'label2On', 'length', 'direction', 'left', 'bottom', 'right', 'top', 'labelleft', 'labelbottom', 'labelright', 'rotation', 'grid_agg_filter', 'grid_alpha', 'grid_animated', 'grid_antialiased', 'grid_clip_box', 'grid_clip_on', 'grid_clip_path', 'grid_colorstyle', 'grid_dash_joinstyle', 'grid_dashes', 'grid_data', 'grid_drawstyle', 'grid_figure', 'grid_fillstyle', 'grid_gapcolor', 'grid_gid', 'griid_label', 'grid_linestyle', 'grid_linewidth', 'grid_marker', 'grid_markeredgecolor', 'grid_markeredgewidth', 'grid_markerfacecolor', 'grid_mar 'grid_markersize', 'grid_markevery', 'grid_mouseover', 'grid_path_effects', 'grid_picker', 'grid_pickradius', 'grid_rasterized', 'grid_sketch_ap', 'grid_solid_capstyle', 'grid_solid_joinstyle', 'grid_transform', 'grid_url', 'grid_visible', 'grid_xdata', 'grid_ydata', 'grid_zorder', 'g, 'grid_ds', 'grid_ls', 'grid_lw', 'grid_mec', 'grid_mew', 'grid_mfc', 'grid_mfcalt', 'grid_ms']

```

Python 3.9.12
intervene  0.6.5
matplotlib 3.7.1
pandas 2.0.3

Any help is appreciated!

**Comment by asntech** [comment]
Hi @Edert can you please try to install `matplotlib<3.7`.
For example `conda install matplotlib==3.4.3`
